# options for the 3x2pt Gaussian covariance matrix computation
# Author: Davide Sciotti

zbins: 10  # number of redshift bins
EP_or_ED: 'EP'  # or 'ED'. Equipopulated or equidistant redshift bins

ell_min: 10  # minimum ell for the angular power spectra
ell_max: 5000  # maximum ell for the angular power spectra
ell_bins: 20  # number of ell bins for the angular power spectra

# alternatively, one can specify the ell grid directly (set to "null" if you prefer to use ell_min, ell_max, ell_bins)
# ell_path: '../input/ell_values.txt'  # path to txt file with the ell grid
# delta_ell_path: '../input/delta_ell_values.txt' # path to txt file with the delta ell grid
ell_path: null
delta_ell_path: null

n_gal_shear: 30  # number of sources per arcmin^2, relevant for weak lensing cosmic shear. 
                 # This scalar must be provided for equipopulated ('EP') redshift bins
n_gal_clustering: 30  # number of lenses per arcmin^2, relevant for photometric galaxy clustering. 
                      # This scalar must be provided for equipopulated ('EP') redshift bins
n_gal_path_shear: null  # path to .txt/.dat file with the number of sources per arcmin^2 *for each redshift bin*,
                   # relevant for weak lensing cosmic shear. This must be provided for equidistant ('ED') redshift bins.
n_gal_path_clustering: null  # path to .txt/.dat file with the number of lenses per arcmin^2 *for each redshift bin*,
                        # relevant for photometric galaxy clustering. This must be provided for equidistant ('ED') redshift bins.

# intrinsic ellipticity dispersion *per component*. The total dispersion is
# sigma_eps = sigma_eps_i * sqrt(2), and the term entering the covariance is sigma_eps^2
sigma_eps_i: 0.26
survey_area: 14_700  # in deg^2


# datavector and covariance ordering options
triu_tril: 'triu'  # or 'tril'. Which elements of the (symmetric) auto-spectra are kept
row_col_major: 'row-major'  # whether the flattening of the spectra is in row-major or column-major order
covariance_ordering_2D: 'probe_ell_zpair' # must be one of ['probe_ell_zpair', 'probe_zpair_ell', 'ell_probe_zpair', 'zpair_probe_ell']
# the naming convention is to have the outermost loop on the left, and the innermost loop on the right; so, e.g.,
# probe_ell_zpair means that the outermost loop is on the probes, the middle loop is on ell and the innermost loop is on zpair
# CLOE v1 needs as input the ell_probe_zpair ordering.
# CLOE v2 needs as input the probe_ell_zpair ordering.
plot_covariance_2D: true  # whether to plot (the log10 of) the 2D covariance matrix

# path to 3d numpy Cls
cl_LL_3D_path: '../input/Cl_LL.npy'
cl_GL_3D_path: '../input/Cl_GL.npy'
cl_GG_3D_path: '../input/Cl_GG.npy'

# Pseudo-Cl covariance
# If False will compute the full-sky covariance (divided by fsky).
# Else, compute the Pseudo-Cls covariance with NaMaster.
part_sky: False

# path to NaMaster workspace
workspace_path: null

# path to mask
mask_path: null

output_folder: '../output'


